
heb_dict = {
    'beth': 'ב',
    'caf': 'כ',
    'pe': 'פ',
    'caf_sofit' : 'ך',
    'he': 'ה',
    'rech': 'ר',
    'pe_sofit': 'ף',
    'heth': 'ח',
    'mixed': '',
    'tsadik': 'צ',
    'kouf' : 'ק',
    'teth': 'ט',
    'noun': 'נ',
    'tav': 'ת',
    'guimel': 'ג',
    'noun_sofit': 'ן',
    'mem_sofit': 'ם',
    'ain': 'ע',
    'youd': 'י',
    'daleth': 'ד',
    'kouf coupe': 'ק',
    'zevel2': '',
    'lamed': 'ל',
    'aleph': 'א',
    'zain': 'ז',
    'chin': 'ש',
    'zevel': '',
    'unknown': '',
    'vav': 'ו',
    'mem': 'מ',
    'tsadik_sofit': 'ץ',
    'sameh': 'ס',
    'vavyoud': ''
}